---
- name: Merge base_groups_* variables and base_groups variable
  ansible.builtin.set_fact:
    base_groups: "{{ base_groups + lookup('vars', item) }}"
  loop: "{{ lookup('varnames', 'base_groups_', wantlist=True) }}"
  tags: base

- name: Create groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    gid: "{{ item.gid | default(omit) }}"
  loop: "{{ base_groups }}"
  tags: base
  become: true
