---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- import_tasks: os.yml
- import_tasks: users.yml
- import_tasks: groups.yml
