---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags: base

- name: OS tasks
  ansible.builtin.import_tasks: os.yml

- name: Group tasks
  ansible.builtin.import_tasks: groups.yml

- name: Users tasks
  ansible.builtin.import_tasks: users.yml
