---
- name: Merge base_users_* variables and base_users variable
  set_fact:
    base_users: "{{ base_users + lookup('vars', item) }}"
  loop: "{{ lookup('varnames', 'base_users_', wantlist=True) }}"
  tags: base

- name: Create users
  user:
    append: true
    create_home: "{{ item.create_home | default(omit) }}"
    generate_ssh_key: "{{ item.generate_ssh_key | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups | default([]) }}"
    home: "{{ item.home | default(omit) }}"
    name: "{{ item.name }}"
    shell: "{{ item.shell | default(omit) }}"
    ssh_key_bits: "{{ item.ssh_key_bits | default(omit) }}"
    ssh_key_comment: "{{ item.ssh_key_comment | default(omit) }}"
    ssh_key_file: "{{ item.ssh_key_file | default(omit) }}"
    ssh_key_passphrase: "{{ item.ssh_key_passphrase | default(omit) }}"
    ssh_key_type: "{{ item.ssh_key_type | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    system: "{{ item.system | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
  loop: "{{ base_users }}"
  tags: base
  become: true

- name: Set authorized keys for users
  authorized_key:
    user: "{{ item.name }}"
    key: "{% for k in item.authorized_keys %}{{ k }}\n{% endfor %}"
    exclusive: "{{ item.authorized_keys_exclusive | default(omit) }}"
    state: present
  loop: "{{ base_users }}"
  tags: base
  become: true
