---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
      become: true
  tasks:
    - name: "Include ansible-role-base"
      ansible.builtin.include_role:
        name: "ansible-role-base"
      tags: always
